import assert from 'node:assert/strict';
import { createAnatomyInput } from '../src/lib/viewer/anatomy-input.ts';

const input = createAnatomyInput();
function release(id, x, y, inside, hit) {
  if (input.up(id, x, y, inside)) input.select(hit);
}
assert.equal(input.select('head'), true);
assert.equal(input.select('head'), false);
assert.equal(input.select(undefined), false);
assert.equal(input.selected, 'head');
input.down(1, 0, 0);
input.move(1, 7, 0);
input.move(1, 0, 0);
release(1, 0, 0, true, null);
assert.equal(input.selected, 'head');
input.down(1, 0, 0);
input.down(2, 10, 0);
release(1, 0, 0, true, 'armor');
release(2, 10, 0, true, null);
assert.equal(input.selected, 'head');
input.down(1, 0, 0);
input.down(2, 10, 0);
input.cancel(1);
release(2, 10, 0, true, 'armor');
assert.equal(input.selected, 'head');
input.down(1, 0, 0);
input.cancel(1);
release(1, 0, 0, true, 'armor');
assert.equal(input.selected, 'head');
input.down(1, 0, 0);
release(1, 0, 0, false, null);
assert.equal(input.selected, 'head');
input.down(1, 0, 0);
release(1, 7, 0, true, 'armor');
assert.equal(input.selected, 'head');
input.down(1, 0, 0);
release(1, 6, 0, true, 'tailClub');
assert.equal(input.selected, 'tailClub');
input.down(1, 0, 0);
input.resetGesture();
release(1, 0, 0, true, null);
assert.equal(input.selected, 'tailClub');
input.down(1, 0, 0);
release(1, 0, 0, true, 'armor');
assert.equal(input.selected, 'armor');
assert.equal(input.select(null), true);
assert.equal(input.selected, null);
assert.equal(input.select(null), false);
console.log('Anatomy selection and gesture assertions passed.');
